### ISSUE TITLE
Problems re-deploying this module to the forge

### ISSUE THREAD

**Issue by liamjbennett** [puppet-community/puppet-windows_autoupdate#17]
I am having issues creating the required secure password in the ```.travis.yml``` file in order for auto-deployment to the forge to work correctly.

I have done the following:

* fresh clone of repo
* gem install travis
* travis pubkey
* travis encrypt -s <my forge password> (include escaping)
* Add the secure string into the .travis.yml file

Having gone through this, including re-creating the tag, many times I am stuck as to why this doesn't work.

You'll see the following issue:
```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/puppet-blacksmith-3.2.0/lib/puppet_blacksmith/forge.rb:51:in `rescue in push!': Error login to the forge https://forgeapi.puppetlabs.com as puppet [400 Bad Request]: {"error":"invalid_grant","error_description":"Username/password do not match"} (Blacksmith::Error)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/puppet-blacksmith-3.2.0/lib/puppet_blacksmith/forge.rb:42:in `push!'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider/puppet_forge.rb:38:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider.rb:132:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider.rb:132:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
```

**Comment by liamjbennett** [comment]
@raphink @nibalizer @igalic - any ideas?

**Comment by raphink** [comment]
Did you link the travis command to the puppet-community repo or yours?

**Comment by liamjbennett** [comment]
When I run ```travis pubkey``` it says ```Public key for puppet-community/puppet-windows_autoupdate:``` so i assume so

**Comment by nibalizer** [comment]
So are you trying to create it under forge.puppetlabs.com/puppet or forge.puppetlabs.com/liamjbennett? the name: "puppet-windows_autoupdate" part is making it try to publish to the 'puppet' user on the forge.

**Comment by liamjbennett** [comment]
I want it to go to: forge.puppetlabs.com/puppet

**Comment by nibalizer** [comment]
Oh well then you probably just don't have the password, unless igalic gave it to you. Let me try encrypting the password to this repo.

**Comment by liamjbennett** [comment]
No i don't have it. Thought that might be the issue.

**Comment by nibalizer** [comment]
https://github.com/puppet-community/puppet-windows_autoupdate/pull/18

**Comment by liamjbennett** [comment]
Awesome, thanks. Can you do the same for the other modules, as I want to get them pushed this week?

**Comment by nibalizer** [comment]
ya ill script it up

**Comment by nibalizer** [comment]
or maybe @raphink and @cmurphy can show me how to use modulesync

**Comment by raphink** [comment]
Modulesync would be good, but it won't solve the password encryption bit.

**Comment by igalic** [comment]
see also https://github.com/puppet-community/puppet-community.github.io/issues/5

**Comment by nibalizer** [comment]
https://github.com/puppet-community/plumbing/blob/travis/share/travis_secrets and https://github.com/puppet-community/plumbing/pull/1

**Comment by raphink** [comment]
Maybe I wasn't clear when I said modulesync won't solve the issue. It *can* deploy `.travis.yml` with the encrypted strings if they are stored in each module's `.sync.yml`, but it *can't* generate the encrypted strings automatically (because that would mean storing the forge password unencrypted in modulesync_configs).

**Comment by liamjbennett** [comment]
Ok, this sort-of worked. 
The module got deployed, which is great :+1: 

However some of the matrix jobs failed, which is my bad for not using the standard (extlib) .travis config. Despite that it did highlight some interesting issues.

I can see from extlib that the deployment is triggered upon the success of the ruby 1.9.3 (touchstone) jobs. This has two limitations that I can see:

1. Limited to one puppet version per ruby version. This is not really an issue for windows modules, because we don't have to care too much about the ruby version but for others this could be.

2. If one of the jobs fails and it's not the touchstone job then the module can get deployed anyway.

If this is not the appropriate place to discuss this then let me know and I will raise an issue else where.

**Comment by nibalizer** [comment]
@liamjbennett so blacksmith was able to handle creating the module? I'm wondering if we can just release using this method or if we need to manually create the module in the forge before blacksmith can work.

**Comment by liamjbennett** [comment]
Yes it worked fine: https://forge.puppetlabs.com/puppet/windows_autoupdate

There was actually nothing wrong with blacksmith. The forge team actually updated the forge some time ago to auto-create the module when you release the first version via the api.

**Comment by nibalizer** [comment]
Awwwwesome.

**Comment by liamjbennett** [comment]
The problem I have now is the the build appears in error because of the issues noted above. 

Should I raise this against the new plumbing project?

**Comment by liamjbennett** [comment]
Moved to the standard travis.yml file and re-released so closing this issue for now.
